### ISSUE TITLE
Tabs have problem

### ISSUE THREAD

**Issue by dessasin** [sonnyp/gigagram#5] opened 2019-07-12 23:08 UTC
Sometimes having problems closing tabs, sometimes not closing itself, sometimes closing other tab

[Video](https://streamable.com/4rb65)

**Comment by sonnyp** [comment] 2019-07-13 12:11
Could you run gigagram from the command line:

```sh
flatpak run re.sonny.gigagram
```

reproduce and share the terminal output?

**Comment by sonnyp** [comment] 2019-07-13 12:17
I could reproduce. On it.

**Comment by dessasin** [comment] 2019-07-13 12:34
`<pre>(re.sonny.gigagram:2): Gjs-<font color="#FCE94F"><b>WARNING</b></font> **: <font color="#3465A4">15:32:30.648</font>: Some code called array.toString() on a Uint8Array instance. Previously this would have interpreted the bytes of the array as a string, but that is nonstandard. In the future this will return the bytes as comma-separated digits. For the time being, the old behavior has been preserved, but please fix your code anyway to explicitly call ByteArray.toString(array).
(Note that array.toString() may have been called implicitly.)
0 load/&lt;() [&quot;resource:///re/sonny/gigagram/js/serviceManager.js&quot;:39]
1 map() [&quot;self-hosted&quot;:285]
2 load() [&quot;resource:///re/sonny/gigagram/js/serviceManager.js&quot;:35]
3 anonymous() [&quot;resource:///re/sonny/gigagram/js/serviceManager.js&quot;:77]
4 &lt;TOP LEVEL&gt; [&quot;resource:///re/sonny/gigagram/js/serviceManager.js&quot;:1]
5 anonymous() [&quot;resource:///re/sonny/gigagram/js/homePage.js&quot;:16]
6 &lt;TOP LEVEL&gt; [&quot;resource:///re/sonny/gigagram/js/homePage.js&quot;:1]
7 anonymous() [&quot;resource:///re/sonny/gigagram/js/window.js&quot;:14]
8 &lt;TOP LEVEL&gt; [&quot;resource:///re/sonny/gigagram/js/window.js&quot;:1]
9 anonymous() [&quot;resource:///re/sonny/gigagram/js/main.js&quot;:14]
10 &lt;TOP LEVEL&gt; [&quot;resource:///re/sonny/gigagram/js/main.js&quot;:1]
11 &lt;TOP LEVEL&gt; [&quot;/app/bin/re.sonny.gigagram&quot;:9]


(re.sonny.gigagram:2): Gjs-<font color="#FCE94F"><b>WARNING</b></font> **: <font color="#3465A4">15:32:30.650</font>: Some code called array.toString() on a Uint8Array instance. Previously this would have interpreted the bytes of the array as a string, but that is nonstandard. In the future this will return the bytes as comma-separated digits. For the time being, the old behavior has been preserved, but please fix your code anyway to explicitly call ByteArray.toString(array).
(Note that array.toString() may have been called implicitly.)
0 load/&lt;() [&quot;resource:///re/sonny/gigagram/js/serviceManager.js&quot;:64]
1 map() [&quot;self-hosted&quot;:285]
2 load() [&quot;resource:///re/sonny/gigagram/js/serviceManager.js&quot;:35]
3 anonymous() [&quot;resource:///re/sonny/gigagram/js/serviceManager.js&quot;:77]
4 &lt;TOP LEVEL&gt; [&quot;resource:///re/sonny/gigagram/js/serviceManager.js&quot;:1]
5 anonymous() [&quot;resource:///re/sonny/gigagram/js/homePage.js&quot;:16]
6 &lt;TOP LEVEL&gt; [&quot;resource:///re/sonny/gigagram/js/homePage.js&quot;:1]
7 anonymous() [&quot;resource:///re/sonny/gigagram/js/window.js&quot;:14]
8 &lt;TOP LEVEL&gt; [&quot;resource:///re/sonny/gigagram/js/window.js&quot;:1]
9 anonymous() [&quot;resource:///re/sonny/gigagram/js/main.js&quot;:14]
10 &lt;TOP LEVEL&gt; [&quot;resource:///re/sonny/gigagram/js/main.js&quot;:1]
11 &lt;TOP LEVEL&gt; [&quot;/app/bin/re.sonny.gigagram&quot;:9]


(WebKitWebProcess:27): Gdk-<font color="#EF2929"><b>ERROR</b></font> **: <font color="#3465A4">15:32:32.483</font>: The program &apos;WebKitWebProcess&apos; received an X Window System error.
This probably reflects a bug in the program.
The error was &apos;BadValue (integer parameter out of range for operation)&apos;.
  (Details: serial 196 error_code 2 request_code 152 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

(WebKitWebProcess:46): Gdk-<font color="#EF2929"><b>ERROR</b></font> **: <font color="#3465A4">15:32:32.494</font>: The program &apos;WebKitWebProcess&apos; received an X Window System error.
This probably reflects a bug in the program.
The error was &apos;BadValue (integer parameter out of range for operation)&apos;.
  (Details: serial 196 error_code 2 request_code 152 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

(WebKitWebProcess:68): Gdk-<font color="#EF2929"><b>ERROR</b></font> **: <font color="#3465A4">15:32:32.744</font>: The program &apos;WebKitWebProcess&apos; received an X Window System error.
This probably reflects a bug in the program.
The error was &apos;BadValue (integer parameter out of range for operation)&apos;.
  (Details: serial 203 error_code 2 request_code 152 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

(WebKitWebProcess:39): Gdk-<font color="#EF2929"><b>ERROR</b></font> **: <font color="#3465A4">15:32:32.874</font>: The program &apos;WebKitWebProcess&apos; received an X Window System error.
This probably reflects a bug in the program.
The error was &apos;BadValue (integer parameter out of range for operation)&apos;.
  (Details: serial 196 error_code 2 request_code 152 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

(WebKitWebProcess:21): Gdk-<font color="#EF2929"><b>ERROR</b></font> **: <font color="#3465A4">15:32:33.422</font>: The program &apos;WebKitWebProcess&apos; received an X Window System error.
This probably reflects a bug in the program.
The error was &apos;BadValue (integer parameter out of range for operation)&apos;.
  (Details: serial 209 error_code 2 request_code 152 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

(WebKitWebProcess:33): Gdk-<font color="#EF2929"><b>ERROR</b></font> **: <font color="#3465A4">15:32:33.473</font>: The program &apos;WebKitWebProcess&apos; received an X Window System error.
This probably reflects a bug in the program.
The error was &apos;BadValue (integer parameter out of range for operation)&apos;.
  (Details: serial 209 error_code 2 request_code 152 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

(re.sonny.gigagram:2): Gtk-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">15:32:44.817</font>: gtk_notebook_get_tab_label: assertion &apos;list != NULL&apos; failed

(re.sonny.gigagram:2): Gtk-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">15:32:49.702</font>: gtk_notebook_get_tab_label: assertion &apos;list != NULL&apos; failed

(re.sonny.gigagram:2): Gtk-<font color="#AD7FA8"><b>CRITICAL</b></font> **: <font color="#3465A4">15:32:54.624</font>: gtk_notebook_get_tab_label: assertion &apos;list != NULL&apos; failed


</pre>`

**Comment by dessasin** [comment] 2019-07-13 12:35
tab closing errors at bottom

**Comment by sonnyp** [comment] 2019-07-13 14:11
ok fixed in master

```
cd gigagram
git pull
# install instructions
```

Can you please confirm and close the issue?

I also changed the way adding a service works, it's now a button in the headerbar instead of a tab.

**Comment by dessasin** [comment] 2019-07-13 17:11
I do not understand the reason, but the problem continues

[Video](https://streamable.com/hei3h)

**Comment by sonnyp** [comment] 2019-07-13 17:39
@dessasin run is not enough, you have to re-build:

```sh
cd gigagram
git pull
flatpak-builder --repo=repo --install-deps-from=flathub flatpak re.sonny.gigagram.yaml
flatpak --user remote-add --no-gpg-verify gigagram repo
flatpak --user install gigagram re.sonny.gigagram
flatpak run re.sonny.gigagram
```

**Comment by dessasin** [comment] 2019-07-13 17:49
I am already rebuilded app.I noticed that the new features are not coming, I wonder if flatpak has a cache?

**Comment by sonnyp** [comment] 2019-07-13 17:56
@dessasin my bad:

```sh
cd gigagram
git pull
flatpak-builder --force-clean --repo=repo --install-deps-from=flathub flatpak re.sonny.gigagram.yaml
flatpak --user remote-add --no-gpg-verify gigagram repo
flatpak --user install --reinstall gigagram re.sonny.gigagram
flatpak run re.sonny.gigagram
```

**Comment by sonnyp** [comment] 2019-07-13 20:19
It's fixed right?

**Comment by dessasin** [comment] 2019-07-13 20:29
> It's fixed right?

Only in test.If I install the application on the system, the problems persist but I do not experience any problems when I do the test with run.sh.

**Comment by sonnyp** [comment] 2019-07-13 20:45
You need to rebuild/reinstall the flatpak

```
cd gigagram
git pull
clear
flatpak-builder --force-clean --repo=repo --install-deps-from=flathub flatpak re.sonny.gigagram.yaml
flatpak --user remote-add  --if-not-exists --no-gpg-verify gigagram repo
flatpak --user install --reinstall gigagram re.sonny.gigagram
flatpak run re.sonny.gigagram
```

Please paste the complete terminal output if it does not work as expected.

**Closed by sonnyp** 2019-07-13 20:45 UTC

**Comment by dessasin** [comment] 2019-07-13 21:13
last try :/

[terminal output](https://paste.ubuntu.com/p/bFG4jvMXP6/)
[vid](https://streamable.com/p37ds)

**Comment by sonnyp** [comment] 2019-07-13 21:20
@dessasin I can't read the output, please copy paste text only, no HTML

**Comment by sonnyp** [comment] 2019-07-13 21:23
Okay I know what the issue is, you're running git pull in your fork, not in this repository.

**Comment by sonnyp** [comment] 2019-07-13 21:23
```sh
git clone https://github.com/sonnyp/gigagram.git
cd gigagram
...
```
